name: Monkeytype Stats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: monkeytype-hub/monkeytype-readme@master
        with:
          username: karnVen
          github-token: ${{ secrets.GITHUB_TOKEN }}
          themes: 'serika_dark'
          target-branch: output
          # These exact names ensure ONLY the heatmap appears
          show-personal-bests: false
          show-leaderboard: false
          show-chart: true
        env:
          MONKEYTYPE_APE_KEY: ${{ secrets.MONKEYTYPE_APE_KEY }}
