name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch: # Allows you to run it manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "" # Hides default GitHub stats to keep it clean
          target: output # Saves to your existing output branch
          plugin_monkeytype: yes
          plugin_monkeytype_token: ${{ secrets.MONKEYTYPE_APE_KEY }}
          plugin_monkeytype_user: karnVen
          plugin_monkeytype_sections: chart # This forces the heatmap grid
