name: Generate pacman animation

on:
  schedule: # Runs at midnight and noon UTC
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          # Use the repository owner's username automatically
          github_user_name: ${{ github.repository_owner }}

      - name: Create dist directory and move file
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # The branch to push the generated file to
          target_branch: output
          # The directory containing the file to push
          build_dir: dist
        env:
          # Use the secure, automatically-generated token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
